---
editor_options:
  markdown:
    wrap: 72
output:
  html_document:
    df_print: paged
---

```{r}
# load required libraries

library(dplyr)
library(maps)
library(spdep)
library(MASS)
library(INLA)
library(inlabru)
library(sf)
library(ggplot2)
library(scoringRules)

```


### Data pre-processing

```{r}
# load data

load("Agrimonia_Dataset_v_3_0_0.Rdata")

df <- AgrImOnIA_Dataset_v_3_0_0

```


```{r}
# create month_id column

df$month_id <- as.integer(format(df$Time, "%m"))

# scale covariate

df$Altitude_sc <- as.numeric(scale(df$Altitude))

```


### Investigate target variable of interest: PM2.5 concentrations

```{r}
# turn 0s into NaNs
df$AQ_pm25[df$AQ_pm25 == 0] <- NaN

# remove NaNs (and 0s) to analyse distribution of PM2.5
complete_case_df <- df[!is.na(df$AQ_pm25), ]
# note: can keep NaNs in modeling bc inla still works, but discludes NaNs in likelihood calculation but still outputs posterior predictions for them which may be useful

# fit log normal with MLE
fit_lnorm <- fitdistr(complete_case_df$AQ_pm25, "lognormal")
meanlog   <- fit_lnorm$estimate["meanlog"]
sdlog     <- fit_lnorm$estimate["sdlog"]

# plot histogram
hist(complete_case_df$AQ_pm25, freq = FALSE,
     main = "PM2.5 with Log-Normal Overlay",
     xlab = "PM2.5 Concentration (µg/m³)",
     col = "lightblue", border = "white",
     ylim = c(0, 0.05))

# overlay density
x_seq <- seq(0, max(complete_case_df$AQ_pm25), length.out = 500)
lines(x_seq, dlnorm(x_seq, meanlog = meanlog, sdlog = sdlog),
      col = "darkgreen", lwd = 2)
legend("topright", 
       legend = c("Observed","Log-Normal"),
       fill   = c("lightblue", NA, NA),
       lty    = c(NA, 1),
       col    = c("lightblue", "darkgreen"),
       lwd    = c(NA, 2))


```



### Create the mesh for spatial effect


```{r}
# obtain only unique locations
unique_locs <- unique(df[, c("Latitude", "Longitude")])

# construct non-convex spatial boundary
statdomain <- inla.nonconvex.hull(
  as.matrix(unique_locs[, c("Longitude", "Latitude")]),
  convex = -0.05,
  concave = -0.3,
  resolution = c(100, 100)
)

# generate mesh over the spatial domain
statmesh <- fmesher::fm_mesh_2d(
  boundary = statdomain,
  max.edge = c(0.15, 0.4),
  cutoff = 0.05
)

# plot the mesh
plot(statmesh)
points(unique_locs[, c("Longitude", "Latitude")], col = "red", pch = 20, cex = 0.5)

```


### Fit each model (M0-M3) with moderately informative priors

```{r, include=FALSE}
# create spatial point locations from longitude/latitude
Locations = data.frame(easting = df$Longitude, northing = df$Latitude)
df$geometry <- sf::st_as_sf(Locations, coords = c("easting", "northing"))$geometry

# SPDE model (Matérn field representation over the mesh)
loc.spde = inla.spde2.pcmatern(
  mesh        = statmesh,
  prior.range = c(1, 0.5),
  prior.sigma = c(1, 0.5),
  constr      = TRUE
)

# set compute options and prior of log-normal precision
bru_opts <- list(
  control.family  = list(
    hyper = list(
      prec = list(prior = "pc.prec", param = c(1, 0.01))
    )
  ),
  control.compute = list(mlik = TRUE, cpo = TRUE, waic = TRUE)
)

# M0: Fixed effects only
cmp_m0 <- AQ_pm25 ~
  Intercept(1,
            mean.linear = 0, prec.linear = 1) +
  Altitude_sc(Altitude_sc,
              mean.linear = 0, prec.linear = 1)

m0_bru <- bru(
  components = cmp_m0,
  family     = "lognormal",
  data       = df,
  options    = bru_opts
)

# M1: Fixed + Temporal effect (rw1)
cmp_m1 <- AQ_pm25 ~
  Intercept(1,
            mean.linear = 0, prec.linear = 1) +
  Altitude_sc(Altitude_sc,
              mean.linear = 0, prec.linear = 1) +
  f(month_id, model = "rw1", cyclic = TRUE,
    hyper = list(prec = list(prior = "pc.prec",
                             param = c(1, 0.01))))

m1_bru <- bru(
  components = cmp_m1,
  family     = "lognormal",
  data       = df,
  options    = bru_opts
)

# M2: Fixed + Spatial effects (SPDE - matern)
cmp_m2 <- AQ_pm25 ~
  Intercept(1,
            mean.linear = 0, prec.linear = 1) +
  Altitude_sc(Altitude_sc,
              mean.linear = 0, prec.linear = 1) +
  floc(geometry, model = loc.spde)

m2_bru <- bru(
  components = cmp_m2,
  family     = "lognormal",
  data       = df,
  options    = bru_opts
)

# M3: Full spatio-temporal
cmp_m3 <- AQ_pm25 ~
  Intercept(1,
            mean.linear = 0, prec.linear = 1) +
  Altitude_sc(Altitude_sc,
              mean.linear = 0, prec.linear = 1) +
  f(month_id, model = "rw1", cyclic = TRUE,
    hyper = list(prec = list(prior = "pc.prec",
                             param = c(1, 0.01)))) +
  floc(geometry, model = loc.spde)

m3_bru <- bru(
  components = cmp_m3,
  family     = "lognormal",
  data       = df,
  options    = bru_opts
)

```


### Model comparison


```{r}
# WAIC
cat("M0 WAIC =",  m0_bru$waic$waic, "\n")
cat("M1 WAIC =",  m1_bru$waic$waic, "\n")
cat("M2 WAIC =",  m2_bru$waic$waic, "\n")
cat("M3 WAIC =",  m3_bru$waic$waic, "\n\n")


# NLSCPO
m0_nlscpo <- -sum(log(m0_bru$cpo$cpo), na.rm = TRUE)
m1_nlscpo <- -sum(log(m1_bru$cpo$cpo), na.rm = TRUE)
m2_nlscpo <- -sum(log(m2_bru$cpo$cpo), na.rm = TRUE)
m3_nlscpo <- -sum(log(m3_bru$cpo$cpo), na.rm = TRUE)

cat("M0 NLSCPO =", m0_nlscpo, "\n")
cat("M1 NLSCPO =", m1_nlscpo, "\n")
cat("M2 NLSCPO =", m2_nlscpo, "\n")
cat("M3 NLSCPO =", m3_nlscpo, "\n\n")


# Marginal log-likelihood
cat("M0 mlik =", m0_bru$mlik[1], "\n")
cat("M1 mlik =", m1_bru$mlik[1], "\n")
cat("M2 mlik =", m2_bru$mlik[1], "\n")
cat("M3 mlik =", m3_bru$mlik[1], "\n")



```


### Sensitivity analysis


```{r}
# Fixed effects (Intercept + covariate):

# function to fit model with different precisions
fit_fixed_prior <- function(prec) {
  cmp <- AQ_pm25 ~ 
    Intercept(1,
            mean.linear = 0,
            prec.linear = prec) + 
    Altitude_sc(Altitude_sc,
                mean.linear=0,
                prec.linear=prec) +      
  f(month_id, model = "rw1", cyclic = TRUE) +
  floc(geometry, model = loc.spde)
  
  bru(
    components = cmp,
    family = "lognormal",
    data = df,
    options = bru_opts
  )
}

# run models
m3_fixed_weak  <- fit_fixed_prior(0.001) # weak
m3_fixed_mod    <- fit_fixed_prior(1) # moderate
m3_fixed_strong  <- fit_fixed_prior(10) # strong

# function to extract effects from each model
extract_marginal <- function(model, param, label) {
  marg <- as.data.frame(model$marginals.fixed[[param]])
  marg$prior_spec <- label
  marg
}

all_params <- c("Intercept", "Altitude_sc")

# extract effects
all_marginals <- bind_rows(
  lapply(all_params, function(p)
    extract_marginal(m3_fixed_weak, p, "Weak")),
  lapply(all_params, function(p)
    extract_marginal(m3_fixed_mod,   p, "Moderate")),
  lapply(all_params, function(p)
    extract_marginal(m3_fixed_strong, p, "Strong"))
) %>%
  mutate(param = rep(rep(all_params, each = nrow(m3_fixed_weak$marginals.fixed[[1]])), 3))

# prepare data for plotting
intercept_df <- dplyr::filter(all_marginals, param == "Intercept")
altitude_df  <- dplyr::filter(all_marginals, param == "Altitude_sc")

# plot posterior density of intercept effect
ggplot(intercept_df, aes(x = x, y = y, colour = prior_spec)) +
  geom_line(linewidth = 0.9) +
  labs(
    title = "Fixed Effect (intercept)",
    x = "Intercept",
    y = "Posterior density",
    colour = "Prior Specification"
  ) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.title = element_text(size = 15, face = "bold")
  )

# plot posterior density of altitude effect
ggplot(altitude_df, aes(x = x, y = y, colour = prior_spec)) +
  geom_line(linewidth = 0.9) +
  labs(
    title = "Fixed Effect (altitude)",
    x = "Altitude",
    y = "Posterior density",
    colour = "Prior Specification"
  ) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.title = element_text(size = 15, face = "bold")
  )

```


```{r}
# Temporal effect (RW1)

# make function to supply model with different temporal effect priors
fit_rw1_prior <- function(u, alpha, label) {
  rw1_hyper <- list(prec = list(prior = "pc.prec", param = c(u, alpha)))
  
  cmp <- AQ_pm25 ~
    Intercept(1, mean.linear = 0, prec.linear = 1) +
    Altitude_sc(Altitude_sc, mean.linear = 0, prec.linear = 1) +
    f(month_id, model = "rw1", cyclic = TRUE, hyper = rw1_hyper) +
    floc(geometry, model = loc.spde)
  
  bru(components = cmp, family = "lognormal",
      data = df, options = bru_opts)
}

# run models
m3_rw1_smooth <- fit_rw1_prior(u = 0.1, alpha = 0.01, label = "Smooth") # weak
m3_rw1_mod    <- fit_rw1_prior(u = 1,   alpha = 0.01, label = "Moderate") # moderate
m3_rw1_flex <- fit_rw1_prior(u = 10, alpha = 0.01, label = "Flexible") # strong

# extract posterior summary of RW1 effect by month
extract_rw1 <- function(model, label) {
  rw1 <- model$summary.random$f
  rw1$prior_spec <- label
  rw1
}

rw1_sens <- bind_rows(
  extract_rw1(m3_rw1_smooth, "Weak"),
  extract_rw1(m3_rw1_mod,    "Moderate"),
  extract_rw1(m3_rw1_flex,   "Strong")
)

# plot temporal effect by month index
ggplot(rw1_sens, aes(x = ID, y = mean, colour = prior_spec,
                      fill = prior_spec)) +
  geom_line(linewidth = 0.9) +
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`),
              alpha = 0.2, colour = NA) +
  labs(title = "RW1 Temporal Effect",
       x = "Month", y = "Temporal Effect",
       colour = "Prior Specification", fill = "Prior Specification") +
  scale_x_continuous(breaks = 1:12,
                     labels = month.abb) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.title = element_text(size = 15, face = "bold")
  )


```


```{r}
# Spatial effect (range, sigma)

# make function to supply different priors to spatial effect
fit_spde_prior <- function(range0, Prange, sigma0, Psigma, label) {
  spde <- inla.spde2.pcmatern(
    mesh        = statmesh,
    prior.range = c(range0, Prange),
    prior.sigma = c(sigma0, Psigma),
    constr=TRUE
  )
  cmp <- AQ_pm25 ~
    Intercept(1, mean.linear = 0, prec.linear = 1) +
    Altitude_sc(Altitude_sc, mean.linear = 0, prec.linear = 1) +
    f(month_id, model = "rw1", cyclic = TRUE,
      hyper = list(prec = list(prior = "pc.prec", param = c(1, 0.01)))) +
    floc(geometry, model = spde)
  
  bru(components = cmp, family = "lognormal",
      data = df, options = bru_opts)
}

# run models
m3_spde_weak  <- fit_spde_prior(0.1, 0.5, 5, 0.5, "Weak") # weak
m3_spde_mod    <- fit_spde_prior(1,   0.5, 1,   0.5, "Moderate") # moderate
m3_spde_strong  <- fit_spde_prior(3,   0.9, 0.5, 0.5, "Strong") # strong

# function to extract the marginal posterior of spatial hyperparameter
extract_spde_marginal <- function(model, param_name, label) {
  marg <- as.data.frame(
    inla.smarginal(model$marginals.hyperpar[[param_name]])
  )
  marg$prior_spec <- label
  marg
}

# extract range
range_sens <- bind_rows(
  extract_spde_marginal(m3_spde_weak, "Range for floc", "Weak"),
  extract_spde_marginal(m3_spde_mod,   "Range for floc", "Moderate"),
  extract_spde_marginal(m3_spde_strong, "Range for floc", "Strong")
)

# plot posterior density of range parameter
ggplot(range_sens, aes(x = x, y = y, colour = prior_spec)) +
  geom_line(linewidth = 0.9) +
  xlim(0,0.22) +
  labs(title = "SPDE Spatial Effect (range)",
       x = "Spatial range (degrees)", y = "Posterior density",
       colour = "Prior Specification") +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.title = element_text(size = 15, face = "bold")
  )

# extract sigma
sigma_sens <- bind_rows(
  extract_spde_marginal(m3_spde_weak, "Stdev for floc", "Weak"),
  extract_spde_marginal(m3_spde_mod,   "Stdev for floc", "Moderate"),
  extract_spde_marginal(m3_spde_strong, "Stdev for floc", "Strong")
)

# plot posterior density of sigma parameter
ggplot(sigma_sens, aes(x = x, y = y, colour = prior_spec)) +
  geom_line(linewidth = 0.9) +
  xlim(0, 4) +
  labs(title = "SPDE Spatial Effect (σ)",
       x = "Spatial standard deviation σ", y = "Posterior density",
       colour = "Prior Specification") +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.title = element_text(size = 15, face = "bold")
  )




```


```{r}
# Log-normal likelihood precision

# function to plug in priors for log-normal
fit_likelihood_prior <- function(u, alpha, label) {
  spde <- inla.spde2.pcmatern(
    mesh        = statmesh,
    prior.range = c(1, 0.5),
    prior.sigma = c(1, 0.5),
    constr      = TRUE
  )
  cmp <- AQ_pm25 ~
    Intercept(1, mean.linear = 0, prec.linear = 1) +
    Altitude_sc(Altitude_sc, mean.linear = 0, prec.linear = 1) +
    f(month_id, model = "rw1", cyclic = TRUE,
      hyper = list(prec = list(prior = "pc.prec", param = c(1, 0.01)))) +
    floc(geometry, model = spde)
  bru(
    components = cmp,
    family     = "lognormal",
    data       = df,
    options    = list(
      control.family  = list(
        hyper = list(
          prec = list(prior = "pc.prec", param = c(u, alpha))
        )
      ),
      control.compute = list(waic = TRUE, cpo = FALSE, config = TRUE)
    )
  )
}

# run models
m3_lik_weak  <- fit_likelihood_prior(u = 10,  alpha = 0.01, label = "Weak") # weak
m3_lik_mod    <- fit_likelihood_prior(u = 1,   alpha = 0.01, label = "Moderate") # moderate
m3_lik_strong  <- fit_likelihood_prior(u = 0.3, alpha = 0.01, label = "Strong") # strong


# extract precision from model
extract_lik_marginal <- function(model, label) {
  marg <- as.data.frame(
    inla.smarginal(
      model$marginals.hyperpar[["Precision for the lognormal observations"]]
    )
  )
  marg$prior_spec <- label
  marg
}

lik_sens <- bind_rows(
  extract_lik_marginal(m3_lik_weak,  "Weak"),
  extract_lik_marginal(m3_lik_mod,    "Moderate"),
  extract_lik_marginal(m3_lik_strong,  "Strong")
)

# plot posteiror density of precision of log-normal likelihood
ggplot(lik_sens, aes(x = x, y = y, colour = prior_spec)) +
  geom_line(linewidth = 0.9) +
  labs(title = "Log-Normal Likelihood Precision",
       x = "Precision", y = "Posterior density",
       colour = "Prior spec") +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.title = element_text(size = 15, face = "bold")
  )


```


```{r, include=FALSE}
# run model with moderate priors again for further analysis

loc.spde <- inla.spde2.pcmatern(
  mesh        = statmesh,
  prior.range = c(1, 0.5),
  prior.sigma = c(1, 0.5),
  constr      = TRUE
)

cmp_m3 <- AQ_pm25 ~
  Intercept(1,
            mean.linear = 0, prec.linear = 1) +
  Altitude_sc(Altitude_sc,
                mean.linear = 0, prec.linear = 1) +
  f(month_id, model = "rw1", cyclic = TRUE,
    hyper = list(prec = list(prior = "pc.prec",
                             param = c(1, 0.01)))) +
  floc(geometry, model = loc.spde)

m3_revised <- bru(
  components = cmp_m3,
  family     = "lognormal",
  data       = df,
  options    = list(
    control.family  = list(
      hyper = list(
        prec = list(prior = "pc.prec", param = c(1, 0.01))
      )
    ),
    control.compute = list(cpo = TRUE, dic=TRUE, config = TRUE, mlik=TRUE, waic=TRUE)
  )
)

```

### Evaluation of model (M3)

```{r}
# sample from posterior

df_obs <- df[!is.na(df$AQ_pm25), ] # disclude rows with missing response (want to compare observed against predicted)
df_obs <- df_obs[which(df_obs$AQ_pm25 > 3.699e-20), ] # remove extreme outlier (was causing issues in the computation of subsequent evaluation metrics)

n_sims <- 500 # produce 500 replicate datasets
y_rep <- matrix(NA, nrow = nrow(df_obs), ncol = n_sims)
post_samples <- inla.posterior.sample(n_sims, m3_revised)

for(i in 1:n_sims){
  s <- post_samples[[i]]
  eta <- s$latent[1:nrow(df_obs)] # extract latent linear predictor
  sigma <- 1 / sqrt(s$hyperpar[[1]]) # extract posterior draw of lognormal SD
  y_rep[, i] <- rlnorm(nrow(df_obs), meanlog = eta, sdlog = sigma) # posterior predictive draw of observations (under log-normal)
}

```


```{r}
# bayesian studentised residuals

# compute studentised residuals
n <- nrow(df_obs)
y <- log(df_obs$AQ_pm25)

X <- cbind(1, df_obs$Altitude_sc)
XtX_inv <- solve(t(X) %*% X)
h <- rowSums((X %*% XtX_inv) * X)

studentisedred <- matrix(NA, nrow = n, ncol = n_sims)
for(l in 1:n_sims){
  s <- post_samples[[l]]
  eta <- s$latent[1:n]                   
  sigma <- 1 / sqrt(s$hyperpar[[1]])
  studentisedred[,l] <- (y - eta) / sqrt(sigma^2 * (1 - h))
}
studentisedredm <- apply(studentisedred, 1, mean)


# qq plot
qqnorm(studentisedredm,
       main="",
       xlab = "Theoretical Quantiles",
       ylab = "Sample Quantiles",
       pch = 16, cex = 0.4, col = "black",
       xlim = c(-3,3), ylim = c(-3,3),
       cex.lab = 1.6) 
qqline(studentisedredm, col = "red", lwd = 1.5)
title(main = "(a)", adj = 0, cex.main = 1.8)



# residuals against index plot
plot(seq_along(studentisedredm), studentisedredm, 
     main="",
     xlab = "Index", 
     ylab = "Studentised Residuals", 
     ylim = c(-8, 8), # there is one extreme observation beyond +- 8, disclude it in analysis as its an obvious outlier
     cex.lab = 1.6,
     pch = 16,      
     cex = 0.2)
title(main = "(b)", adj = 0, cex.main = 1.8)


# residuals against posterior mean of fitted values
fittedvalues <- matrix(0, nrow = n, ncol = n_sims)
for(i in 1:n_sims){
  s <- post_samples[[i]]
  eta <- s$latent[1:n]
  fittedvalues[, i] <- exp(eta)
}

fittedvaluesm<-numeric(n)
for(i in 1:n){fittedvaluesm[i]=mean(fittedvalues[i,])}
plot(fittedvaluesm,studentisedredm,
     main="",
     xlab="Fitted value (posterior mean)",
     ylab="Studentised Residuals",
     ylim=c(-8, 8), # get rid of that same outlier here too
     pch = 16,
     cex.lab = 1.6,
     cex=0.2)
title(main = "(c)", adj = 0, cex.main = 1.8)



```



```{r}
# histogram of sampled stats and observed ones

# get summary stats of generated data
yrepmin <- apply(y_rep, 2, min)
yrepmax <- apply(y_rep, 2, max)
yrepmedian <- apply(y_rep, 2, median)
require(fBasics)
yrepskewness <- apply(y_rep, 2, skewness)

# get summary stats of observed data
obs_min <- min(df_obs$AQ_pm25)
obs_max <- max(df_obs$AQ_pm25)
obs_median <- median(df_obs$AQ_pm25)
obs_skewness <- skewness(df_obs$AQ_pm25)

# plot of minimum values
hist(yrepmin,
     main = "",
     xlab = expression(paste("Minimum PM"[2.5], " (", mu, "g m"^{-3}, ")")),
     col = "skyblue3",
     border = "white",
     breaks = 20,
     xlim = c(0, 1),
     cex.lab = 1.6)
abline(v = obs_min, col = "red", lwd = 2)
title(main = "(a)", adj = 0, cex.main = 1.8)

# plot of maximum values
hist(yrepmax,
     main = "",
     xlab = expression(paste("Maximum PM"[2.5], " (", mu, "g m"^{-3}, ")")),
     col = "skyblue3",
     border = "white",
     breaks = 20,
     xlim = c(min(yrepmax, obs_max), 850),
     cex.lab = 1.6)
abline(v = obs_max, col = "red", lwd = 2)
title(main = "(b)", adj = 0, cex.main = 1.8)

# plot of median values
hist(yrepmedian,
     main = "",
     xlab = expression(paste("Median PM"[2.5], " (", mu, "g m"^{-3}, ")")),
     col = "skyblue3",
     border = "white",
     breaks = 20,
     xlim = c(14, 17.5),
     cex.lab = 1.6)
abline(v = obs_median, col = "red", lwd = 2)
title(main = "(c)", adj = 0, cex.main = 1.8)

# plot of skewness values
hist(yrepskewness,
     main = "",
     xlab = expression(paste("Skewness PM"[2.5])),
     col = "skyblue3",
     border = "white",
     breaks = 20,
     xlim = c(min(yrepskewness, obs_skewness), 4),
     cex.lab = 1.6)
abline(v = obs_skewness, col = "red", lwd = 2)
title(main = "(d)", adj = 0, cex.main = 1.8)


```



```{r}
# calculate continuous ranked probability score (CRPS)

crps_values <- crps_sample(y = df_obs$AQ_pm25, dat = y_rep)
crps_mean <- mean(crps_values)

cat("CRPS =", round(crps_mean, 3), "\n")

```

### Visualise the random effects


```{r}

# temporal effect
plot(m3_revised$summary.random$f$mean,
     type = "l",
     xlab = "Month Index",
     ylab = "Mean Effect",
     lwd = 2,
     col = "steelblue",
     bty = "l",
     las = 1,
     cex.lab = 1.3,
     cex.axis = 1.1)
grid()

# spatial effect
meshlocs <- as.data.frame(statmesh$loc); names(meshlocs) <- c("lon","lat")
ggplot(meshlocs, aes(x = lon, y = lat, color = m3_revised$summary.random$floc$mean)) +
  geom_point(size = 2) +
  scale_color_viridis_c() +
  coord_equal() +
  theme_minimal() +
  labs(title = "",
       color = "Effect",
       xlab="Longitude",
       ylab="Latitude")


```


### Fixed effect results


```{r}
# calculate fixed effects
effects <- m3_revised$summary.fixed

effects

# obtain exp(fixed effects) for interpretability
effects_exp <- exp(effectd)

effects_exp

```



